export interface Env {
  TELEGRAM_BOT_TOKEN?: string;
  TELEGRAM_WEBHOOK_SECRET?: string;
  TELEGRAM_OWNER_USER_ID?: string;
  REGISTRY_KV?: KVNamespace;
  GITHUB_API_TOKEN?: string;
  V2BOARD_BASE_URL?: string;
  V2BOARD_SUBSCRIBE_PATH?: string;
  V2BOARD_ACCESS_CLIENT_ID?: string;
  V2BOARD_ACCESS_CLIENT_SECRET?: string;
  V2BOARD_CONTROL_AUTH_DATA?: string;
  V2BOARD_CONTROL_ADMIN_PREFIX?: string;
}
